### ISSUE TITLE
Landingpage

### ISSUE THREAD

**Issue by catakul** [catakul/Capstone-Project#16]
## Value Proposition

**As a** user
**I need** a button to navigate 
**to be able to** navigate from the Ladingpage to the app itself

## Description
![Landingpage](https://user-images.githubusercontent.com/106112634/207814085-3b041936-c6d9-4bb0-8cba-7a4a5309e78b.png)

## Acceptance Criteria

- [ ] when clicking the "get started" button, the user can navigate to the actual App

## Tasks

(for developers team)

- [ ] create a landing page
- [ ] add a button which leads to the App using react router
- [ ] add styles for the landingpage
