### ISSUE TITLE
Building the periodic table of elements

### ISSUE THREAD

**Issue by catakul** [catakul/Capstone-Project#2]
## Value Proposition

**As a** user
**I need** a css grid displaying the Elements in order
**to be able to** scrolls left and right, so that the whole PTOF can be displayed on mobile devices

## Description
![Bildschirmfoto 2022-07-20 um 16 30 02](https://user-images.githubusercontent.com/106112634/180008138-faed8c8f-bd40-4f85-bcaf-b176df9cc1ee.png)
![Bildschirmfoto 2022-07-20 um 16 30 08](https://user-images.githubusercontent.com/106112634/180008157-66c66d5e-eb7a-41ec-93ac-1e3036980170.png)

## Acceptance Criteria

- [ ] the User must be able to scroll horizontally in order to see the whole PTOE 

## Tasks

(for developers team)

- [x] create a Css grid to rebuild the PTOE
- [x] Extract data (Element Symbol, Number and Name) using the JSON file
