### ISSUE TITLE
Element cards functions

### ISSUE THREAD

**Issue by catakul** [catakul/Capstone-Project#3]
## Value Proposition

**As a** user
**I need** two buttons to quickly navigate between the previous or next element.
**to be able to** switch between the cards

## Description

<img width="156" alt="Bildschirmfoto 2022-07-20 um 16 24 13" src="https://user-images.githubusercontent.com/106112634/180006746-0b4c294b-69f5-42bd-8125-2c374a8f3d27.png">

## Acceptance Criteria

- [ ] on clicking the arrow buttons, the user can switch between to the previews or the next card displaying the elements
- [ ] underneath the element card a box is displayed, showing the elements order number and the group it belongs to

## Tasks

(for developers team)

- [ ] add two buttons, which switch the displayed element card by its order number (1, 2, 3, 4...)
- [ ] add a box which displays the order number and highlights the group which the element belongs to. (Exp. Helim is a noble gas)
- [ ] add styles
- [ ] add to storybook

**Comment by PReichetanz** [comment]
Hi Cengiz,

some remarks:

- Is this a rework of the list of all fetched elements in catakul/Capstone-Project#4 or is this a different page? I am just wondering where the detailed information of your first story are displayed now. If it's a different page, you also need a link between both pages.

## Value Proposition
- I would adjust the value proposition from the user's point of view: "...I need a detailed card with shortlinks to the previous / next element to be able to quickly navigate between the details view." or something similar.

## Acceptance criteria
- If this is the only page for now: Is "He" the initial element fetched and displayed when the user opens the app? You should state this here.

**Comment by catakul** [comment]
Hey Paul,

no it is not a rework. It is the same page only with added features. 
The added features are the box displaying the group of the element and the buttons to navigate between the elements.
The detailed information of my first User Story [Element cards](https://github.com/catakul/Capstone-Project/issues/4) is still present, but I did not see a reason to display it in this User Story again since it is not relevant in my 2nd User Story.

edit: Acceptance criteria:
No the "He" element is not the initial element fetched and displayed. It is the second, Hydrogen (H) is the default element which is displayed. I used "He" here as an example, so to buttons for switching between the previews and next elements makes sense. If I would have displayed "H" Hydrogen here, there would be no text displayed in the previews button, since Hydrogen is the first element of the periodic table.
