### ISSUE TITLE
Element cards

### ISSUE THREAD

**Issue by catakul** [catakul/Capstone-Project#4]
## Value Proposition

**As a** User
**I need** 
**to be able to**  click on the element cards which will display information for each element

## Description
<img width="193" alt="Bildschirmfoto 2022-07-20 um 16 16 16" src="https://user-images.githubusercontent.com/106112634/180005007-e96e758d-9edb-4292-959b-f80d7ca38060.png">
<img width="199" alt="Bildschirmfoto 2022-07-20 um 16 16 23" src="https://user-images.githubusercontent.com/106112634/180005025-8934bf08-050d-47af-a2d6-9a836422806e.png">

## Acceptance Criteria

- [ ] all 118 Elements data must be extracted and displayed in individual cards as shown on the image above
- [ ] when a card is displayed the user must be able to scroll down to see all the information on that particular element

## Tasks

(for developers team)

- [x] Create feature branch
- [x] create a JSON file containing an Array filled with informations on all the elements
- [x] using React Modals to create popup windows
- [ ] fill the popup windows with the informations from the JSON file

**Comment by PReichetanz** [comment]
Hi Cengiz,

a really good start for your user story! 🎉

💬 Let's discuss some issues which came to my mind while reading:

## General
- How many cards should be displayed? Is it only one or do you want to fetch more? Please be more precise and adapt your description / acceptance criteria if necessary.

## Value Proposition
- I think it should rather be the user than the author.
- I would put the second part of the "I need" line into the third line, because fetching data is the technical concept, but you want to see the elements in your app.

**Comment by catakul** [comment]
Hey Paul,

thanks for the review!
I updated my User Story and I think this time the description is precise enough.
Another check up is appreciated!

**Comment by PReichetanz** [comment]
> Hey Paul,
> 
> thanks for the review! I updated my User Story and I think this time the description is precise enough. Another check up is appreciated!

Hi Cengiz,

it's better, yes! To nit-pick a little bit regarding the value proposition: The user does not "need to fetch data from the periodic table API", because it's a technical issue the user does not care about; the user needs a list of all elements to be able to have an overview.
