### ISSUE TITLE
Periodensystem (User Story in progress!)

### ISSUE THREAD

**Issue by catakul** [catakul/Capstone-Project#5]
## Value Proposition

**As a** user
**I need** recreating the periodic table of elements
**to be able to** to access the periodic table API and recall the properties of each Element

## Description

![Bildschirmfoto 2022-07-20 um 11 44 13](https://user-images.githubusercontent.com/106112634/179951860-14be0c5d-e74d-4bd5-bb9b-30e71c298891.png)

## Acceptance Criteria

- [ ] Build the elements of the periodic table using cards
- [ ] When clicking on a card, a pop-up window appears showcasing the properties of each Element
- [ ] ...

## Tasks

(for developers team)

- [ ] Build a periodic table component
- [ ] Connect each card with the periodic table API
- [ ] Write a storybook
